@DataIngestion.API_HostAddress = http://localhost:5001

GET {{DataIngestion.API_HostAddress}}/health
Accept: application/json

###

GET {{DataIngestion.API_HostAddress}}/
Accept: application/json

###
